//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "CONSUME_PRODT_DETAIL")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub timestamp: DateTime,
    pub cur_timestamp: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub prodt_name: String,
    pub prodt_money: i32,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
