//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "CONSUME_PRODT_KEYWORD")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub consume_keyword_type: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub consume_keyword: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
